# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [3]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [18]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')   
df = df.rename(columns={'st': 'state'})
print(df['state'].unique())
df.head()

<StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,Female,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,Female,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,Male,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,Male,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [19]:
# --- Columna: 'gender' ---
print("Valores únicos 'gender' ANTES:", df['gender'].unique())

gender_mapping = {
    'F': 'Female',
    'Femal': 'Female',
    'Female': 'Female',
    'M': 'Male',
    'Male': 'Male'
}
df['gender'] = df['gender'].replace(gender_mapping)
print("Valores únicos 'gender' DESPUÉS:", df['gender'].unique())

Valores únicos 'gender' ANTES: <StringArray>
[nan, 'Female', 'Male']
Length: 3, dtype: str
Valores únicos 'gender' DESPUÉS: <StringArray>
[nan, 'Female', 'Male']
Length: 3, dtype: str

In [20]:
# --- Columna: 'state' ---
print("Valores únicos 'state' ANTES:", df['state'].unique())

state_mapping = {
    'AZ': 'Arizona',
    'Cali': 'California',
    'California': 'California',
    'Arizona': 'Arizona',
    'WA': 'Washington',
    'Washington': 'Washington',
    'NV': 'Nevada',
    'Nevada': 'Nevada',
    'OR': 'Oregon',
    'Oregon': 'Oregon'
}
df['state'] = df['state'].replace(state_mapping)
print("Valores únicos 'state' DESPUÉS:", df['state'].unique())
print("-" * 50)

Valores únicos 'state' ANTES: <StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str
Valores únicos 'state' DESPUÉS: <StringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str
--------------------------------------------------

In [21]:
df['education'] = df['education'].replace({'Bachelors': 'Bachelor'})

df['vehicle_class'] = df['vehicle_class'].replace({'Sports Car': 'Luxury', 'Luxury SUV': 'Luxury', 'Luxury Car': 'Luxury'})

df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,Female,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,Female,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,Male,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,Male,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [12]:
df['customer_lifetime_value'] = df['customer_lifetime_value'].str.replace('%', '', regex=False)

df['customer_lifetime_value'] = pd.to_numeric(df['customer_lifetime_value'], errors='coerce')

df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [26]:

import numpy as np
import pandas as pd


def extraer_valor_medio_estricto(val):
    # Si ya es nulo, lo mantenemos como tal
    if pd.isna(val):
        return np.nan

    val_str = str(val).strip()

    # Nos ceñimos estrictamente al patrón con '/' solicitado
    if "/" in val_str:
        partes = val_str.split("/")
        # Filtramos posibles espacios vacíos
        partes = [p.strip() for p in partes if p.strip() != ""]

        # Para un formato tipo '1/5/00', la lista tiene 3 elementos; el medio es el índice 1
        if len(partes) >= 3:
            return partes[1]
        elif len(partes) == 2:
            return partes[
                0
            ]  # Manejo seguro si solo viniera un separador (ej. '1/5')
        elif len(partes) == 1:
            return partes[0]

    # Si no cumple el patrón del ejercicio, devolvemos NaN para evitar inconsistencias de texto
    return np.nan


# Aseguramos el nombre estandarizado de la columna (con guiones bajos)
df["number_of_open_complaints"] = df["number_of_open_complaints"].apply(
    extraer_valor_medio_estricto
)

# Convertimos a numérico de forma segura
df["number_of_open_complaints"] = pd.to_numeric(
    df["number_of_open_complaints"], errors="coerce"
)

In [27]:
# ==============================================================================
# VERIFICACIÓN DE CONSISTENCIA Y TIPOS DE DATOS
# ==============================================================================

columnas_verificar = ["customer_lifetime_value", "number_of_open_complaints"]

print("--- Tipos de datos de las columnas verificadas ---")
print(df[columnas_verificar].dtypes)
print("-" * 50)

print("--- Primeros registros para inspección visual ---")
df[columnas_verificar].head()

--- Tipos de datos de las columnas verificadas ---
customer_lifetime_value      float64
number_of_open_complaints    float64
dtype: object
--------------------------------------------------
--- Primeros registros para inspección visual ---

   customer_lifetime_value  number_of_open_complaints
1                697953.59                        NaN
2               1288743.17                        NaN
3                764586.18                        NaN
4                536307.65                        NaN
5                825629.78                        NaN

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [20]:
df.isnull()

,customer,state,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4003,False,False,False,False,False,False,False,True,False,False,False
4004,False,False,False,False,False,False,False,True,False,False,False
4005,False,False,False,False,False,False,False,True,False,False,False
4006,False,False,False,False,False,False,False,True,False,False,False
4007,False,False,False,False,False,False,False,True,False,False,False

In [28]:
# Ahora la lista es 100% consistente con el resto del notebook
columnas_num = [
    'customer_lifetime_value', 
    'income', 
    'monthly_premium_auto', 
    'number_of_open_complaints', 
    'total_claim_amount'
]

# Imputamos los nulos con la mediana de forma segura
for col in columnas_num:
    if col in df.columns:
        # Aseguramos que sea numérico antes de calcular la mediana
        df[col] = pd.to_numeric(df[col], errors='coerce')
        mediana = df[col].median()
        df[col] = df[col].fillna(mediana)

In [30]:
# Buscamos la moda (el valor más común, ej. 'Female')
moda_gender = df['gender'].mode()[0]

# Rellenamos los nulos de forma persistente
df['gender'] = df['gender'].fillna(moda_gender)

# Comprobamos directamente
print(df.isnull().sum())

customer                       0
state                          0
gender                         0
education                      0
customer_lifetime_value        0
income                         0
monthly_premium_auto           0
number_of_open_complaints    954
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [31]:
# ==============================================================================
# 1. IMPUTACIÓN DE LOS NULOS RESTANTES EN 'number_of_open_complaints'
# ==============================================================================
# Calculamos la mediana de las quejas abiertas
mediana_quejas = df["number_of_open_complaints"].median()

# Rellenamos los 954 nulos de forma persistente
df["number_of_open_complaints"] = df["number_of_open_complaints"].fillna(
    mediana_quejas
)

# ==============================================================================
# 2. CONVERSIÓN AUTOMATIZADA DE TODAS LAS VARIABLES NUMÉRICAS A ENTEROS
# ==============================================================================
# Identificamos dinámicamente qué columnas son numéricas en el DataFrame
columnas_numericas = df.select_dtypes(include=["number"]).columns

# Aplicamos la conversión a int64 de forma persistente
for col in columnas_numericas:
    df[col] = df[col].astype("int64")

# ==============================================================================
# 3. VERIFICACIÓN FINAL COMPLETA (Tipos y Nulos)
# ==============================================================================
print("--- COMPROBACIÓN FINAL DE VALORES NULOS ---")
print(df.isnull().sum())
print("-" * 50)

print("--- COMPROBACIÓN FINAL DE TIPOS DE DATOS ---")
print(df[columnas_numericas].dtypes)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [14]:
# ==============================================================================
# PASO 1: Identificación y exploración de filas duplicadas
# ==============================================================================
# Usamos .duplicated() para contar cuántas filas exactas están repetidas
total_duplicados = df.duplicated().sum()
print(f"Análisis inicial: Se encontraron {total_duplicados} filas completamente duplicadas.")

# ==============================================================================
# PASO 2: Estrategia, eliminación persistente y reseteo de índice
# ==============================================================================
"""
DOCUMENTACIÓN Y JUSTIFICACIÓN:
Estrategia: Eliminación completa de registros duplicados manteniendo la primera ocurrencia (keep='first').
Razonamiento: Cada fila representa una entidad única (cliente/póliza). Las filas idénticas en todas 
sus columnas son anomalías (errores de duplicación en la carga de datos). Mantenerlas sesgaría 
los análisis estadísticos (como medias y varianzas) al inflar artificialmente ciertos perfiles.
"""

# Eliminamos duplicados y REASIGNAMOS a 'df' para que el cambio sea persistente
df = df.drop_duplicates(keep='first')

# Reseteamos el índice para mantener la consistencia secuencial (0, 1, 2...) tras borrar filas
# 'drop=True' evita que el índice desordenado viejo se convierta en una columna nueva
df = df.reset_index(drop=True)
print("-> Duplicados eliminados e índice reseteado con éxito.")

# ==============================================================================
# PASO 3: Verificación del éxito del proceso
# ==============================================================================
# Comprobamos de nuevo con .duplicated() para asegurar que el contador baje a 0
duplicados_post = df.duplicated().sum()
print(f"Verificación final: Filas duplicadas restantes = {duplicados_post}")

# ==============================================================================
# PASO 4: Guardado del dataset limpio en un nuevo archivo CSV
# ==============================================================================
# Exportamos a CSV usando index=False para no añadir una columna de índices innecesaria
archivo_salida = 'customer_analysis_clean.csv'
df.to_csv(archivo_salida, index=False)
print(f"-> Archivo de cierre exportado correctamente como: '{archivo_salida}'")

# Visualización de control
df.head()

Análisis inicial: Se encontraron 2936 filas completamente duplicadas.
-> Duplicados eliminados e índice reseteado con éxito.
Verificación final: Filas duplicadas restantes = 0
-> Archivo de cierre exportado correctamente como: 'customer_analysis_clean.csv'

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

In [49]:
df.duplicated().any()

np.False_

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
import pandas as pd

# ==============================================================================
# 1. ASEGURAR TIPOS DE DATOS CORRECTOS
# ==============================================================================
# Nos aseguramos de que las columnas críticas sean numéricas antes de los cuantiles
columnas_analisis = ["income", "customer_lifetime_value"]

for col in columnas_analisis:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Eliminamos filas que hayan quedado con NaN en estas columnas para no falsear los percentiles
df_base_limpia = df.dropna(subset=columnas_analisis)

# ==============================================================================
# 2. CÁLCULO DE UMBRALES (PERCENTILES)
# ==============================================================================
# Definimos los percentiles con nombres claros y específicos
UMBRAL_INCOME_PERCENTIL_25 = df_base_limpia["income"].quantile(0.25)
UMBRAL_CLV_PERCENTIL_75 = df_base_limpia["customer_lifetime_value"].quantile(
    0.75
)

print("--- Umbrales Calculados para el Filtro ---")
print(f"Percentil 25 de Income (Mínimo): {UMBRAL_INCOME_PERCENTIL_25}")
print(f"Percentil 75 de CLV (Mínimo): {UMBRAL_CLV_PERCENTIL_75}\n")

# ==============================================================================
# 3. FILTRADO SIMULTÁNEO Y SELECCIÓN DE COLUMNAS
# ==============================================================================
# Aplicamos ambas condiciones a la vez (Filtro Cruzado)
condicion_income = df_base_limpia["income"] >= UMBRAL_INCOME_PERCENTIL_25
condicion_clv = (
    df_base_limpia["customer_lifetime_value"] >= UMBRAL_CLV_PERCENTIL_75
)

# Creamos un DataFrame con un nombre descriptivo que contiene solo el subconjunto filtrado
df_clientes_alto_valor = df_base_limpia[
    condicion_income & condicion_clv
].copy()

# ==============================================================================
# 4. VISUALIZACIÓN Y DESCRIPCIÓN ESTADÍSTICA
# ==============================================================================
print("--- RESUMEN ESTADÍSTICO DEL SUBCONJUNTO FILTRADO ---")
# Seleccionamos ambas columnas simultáneamente y aplicamos .describe()
estadisticas_subconjunto = df_clientes_alto_valor[columnas_analisis].describe()
print(estadisticas_subconjunto)

print("\n--- VISTA PREVIA DEL DATAFRAME FILTRADO (Inspección Clara) ---")
# Mostramos las primeras filas del subconjunto centrándonos en las columnas clave
df_clientes_alto_valor[columnas_analisis].head(10)

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here